### ISSUE TITLE
Problem with "recursive" meck mocks

### ISSUE THREAD

**Issue by qrilka** [eproxus/meck#119]
See this branch - https://github.com/qrilka/meck_test/tree/recursive_meck
For demonstration purposes I've added a failing match https://github.com/qrilka/meck_test/blob/recursive_meck/apps/app/src/a.erl#L18 which shows the problem:
somehow test "still linger in the old code" (see http://erlang.org/doc/man/code.html#purge-1 ) of the mocked module "b" and meck:unload kills it, so without that match `rebar eunit` gives:

```
*unexpected termination of test process*
::killed
```

And that problem does not appear on the 1st unload (when b unloads a)

So it appears that meck does not support tests when 2 modules try to "meck" each other.
I could not find a way to resolve this issue.

**Comment by tbhavs** [comment]
@eproxus  You explanation saved the day!!!
