### ISSUE TITLE
Please push latest version to Hex

### ISSUE THREAD

**Issue by antipax** [eproxus/meck#146]
Hi, I use your library and it seems the version on Hex is quite outdated and incompatible with OTP 18 and Elixir 1.0.5, perhaps now would be a good time to push an update?

Thanks!

**Comment by tsloughter** [comment]
Since meck uses rebar you might be also interested in publishing to hex with rebar3 :) http://www.rebar3.org/v3.0/docs/publishing-packages

**Comment by eproxus** [comment]
Thanks for reporting!

`mix` has stopped working with a `package.exs` file, so I can't publish right now. Will take a look at switching to rebar3 if I can't figure it out.

**Comment by ericmj** [comment]
@eproxus What stopped working?

**Comment by eproxus** [comment]
@ericmj Sorry, just needed to refresh my memory a bit. :-)

I used `MIX_EXS=package.exs mix hex.publish` and forgot to set `MIX_EXS`. It works now.

**Comment by antipax** [comment]
Thanks @eproxus!
