### ISSUE TITLE
Couldn't find hamcrest.hrl

### ISSUE THREAD

**Issue by LucianoBernal** [eproxus/meck#149]
![failtest](https://cloud.githubusercontent.com/assets/7193325/8984320/31d13d82-36a7-11e5-90e5-0ef8385ce197.png)

Sorry, I have this error, how may I solve it. 
Thanks!!

**Comment by eproxus** [comment]
To run the tests, you need to get the dependencies for Meck. This is done through a special Rebar configuration file, `test.config`. This is done automatically when running `make test`. Perhaps you need to set this up manually in your IDE environment?

**Comment by LucianoBernal** [comment]
Great!! Worked setting that up manually. Thanks!! :)

**Comment by eproxus** [comment]
Good that it worked. Let me know if you have any other questions. :smile:
