### ISSUE TITLE
almost 8x overhead

### ISSUE THREAD

**Issue by albertnetymk** [eproxus/meck#159]
```erlang
-module(test_meck).
-mode(compile).

-include_lib("proper/include/proper.hrl").

-compile(export_all).

prop_l() ->
  ?FORALL(V, ?LET(L, integer(1,100), vector(L, integer())), V =:= V).

test() ->
  proper:quickcheck(prop_l(), [quiet, 1000]).

main(_) ->
  R1 = timer:tc(fun () -> test() end),
  io:format("~p~n", [R1]),
  meck:new(proper, [passthrough]),
  R2 = timer:tc(fun () -> test() end),
  io:format("~p~n", [R2]),
  meck:unload(proper),
  ok.
```

Run it:
```
$ erlc test_meck.erl && erl -noshell -eval 'test_meck:main(1), halt().'
{74522,true}
{649360,true}
```

Any way to bring down the overhead?

**Comment by eproxus** [comment]
Why are you mocking PropEr? There should really be no reason to mock another test tool with Meck.

As regards to the performance loss, Meck `passthrough` just calls the original module which results in one more external call. Perhaps PropEr is calling itself a lot and this causes extra overhead.

**Comment by albertnetymk** [comment]
I testing code written using PropEr; and need to pass `quiet` option to `quickcheck`, sth like:
```
  meck:new(proper, [passthrough]),
  Fun =
    fun(Prop, Opts) ->
        meck:passthrough([Prop, [quiet|Opts]])
    end,
  meck:expect(proper, quickcheck, Fun),
```
OK, that hypothesis makes a lot sense. Any way I could mock only one function within one particular module instead of the whole module? `quickcheck` in `proper` in this case.

**Comment by eproxus** [comment]
No, there is no way in Erlang to mock just one function in a module. The whole module must be replaced.

So, you cannot pass those options because you don't have the source code of the tests?

**Comment by albertnetymk** [comment]
OK. thanks for the info. The source is generally not available.

I had a quick look at [proper module](https://github.com/manopapad/proper/blob/20e62bc32f9bd43fe2ff52944a4ef99eb71d1399/src/proper.erl) based on your hypothesis:
In each run, `proper:run` is called, which calls `proper_gen:safe_generate`, which calls `generate` (in `proper_gen`), which calls `normal_gen` (in `proper_gen`), which calls `proper:get_size`.

According to that it's true that `proper` module is accessed quite many times; therefore the high overhead. Thank you very much for the help.
