### ISSUE TITLE
Memory leak in 0.8.4?

### ISSUE THREAD

**Issue by aherranz** [eproxus/meck#160]
Hi, we made a mistake that led to deploy a release running meck in production.

After weeks the app crashed due to memory allocation issue:

```text
Slogan: eheap_alloc: Cannot allocate 1318267840 bytes of memory (of type "old_heap", thread 1).
```

The mocked module was zen_logic: `meck:new(zen_logic,[passthrough])`. No functions were mocked in fact. The `crashdump_viewer` revealed that the process `zen_logic_meck` was consuming 1Gb.

The process consumes 188K when it starts and I have checked that after hours running the same process was already consuming 64Mb.

Could this reveal any kind of memory leak issue?

**Comment by eproxus** [comment]
Well, yes. :smile: Meck stores a history of calls, that is never cleaned up unless you unmock the module. This history most likely filled up your memory. I would suggest not running active mocks for a longer time if you are constrained by memory, and especially not in production. :wink:

**Comment by aherranz** [comment]
;)

Thanks!
