### ISSUE TITLE
Meck comsumes memory with no_history options

### ISSUE THREAD

**Issue by michalrw** [eproxus/meck#164]
Meck gen_server consumes hundreds of MBs of memory despite use of no_history option.

## Reproduction Steps

1. Meck module
2. Set expect on chosen function
3. Call function many times

## Expected behavior

I use meck to change behaviour of single function in long running test. Meck should not consume significant amount of memory when called many times if no history is needed.

## Observed behavior
Meck consumes small amount of memory each time mocked function is called.

## Versions

**Meck version:** 0.8.4
**Erlang version:** 18

**Comment by eproxus** [comment]
I cannot reproduce this. Trying with the following shell session:

```erl
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> meck:new(foo, [non_strict, no_history]).
ok
2> meck:expect(foo, f, 0, ok).
ok
3> erlang:process_info(whereis(foo_meck)).
[{registered_name,foo_meck},
 {current_function,{gen_server,loop,6}},
 {initial_call,{proc_lib,init_p,5}},
 {status,waiting},
 {message_queue_len,0},
 {messages,[]},
 {links,[<0.13027.0>]},
 {dictionary,[{'$ancestors',[<0.13027.0>]},
              {'$initial_call',{meck_proc,init,1}}]},
 {trap_exit,true},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<0.26.0>},
 {total_heap_size,1974},
 {heap_size,987},
 {stack_size,9},
 {reductions,227},
 {garbage_collection,[{min_bin_vheap_size,46422},
                      {min_heap_size,233},
                      {fullsweep_after,65535},
                      {minor_gcs,1}]},
 {suspending,[]}]
4> [foo:f() || _ <- lists:seq(1, 10000000)].
[ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,
 ok,ok,ok,ok,ok,ok,ok,ok,ok,ok|...]
5> erlang:process_info(whereis(foo_meck)).
[{registered_name,foo_meck},
 {current_function,{gen_server,loop,6}},
 {initial_call,{proc_lib,init_p,5}},
 {status,waiting},
 {message_queue_len,0},
 {messages,[]},
 {links,[<0.13027.0>]},
 {dictionary,[{'$ancestors',[<0.13027.0>]},
              {'$initial_call',{meck_proc,init,1}}]},
 {trap_exit,true},
 {error_handler,error_handler},
 {priority,normal},
 {group_leader,<0.26.0>},
 {total_heap_size,1974},
 {heap_size,376},
 {stack_size,9},
 {reductions,373085722},
 {garbage_collection,[{min_bin_vheap_size,46422},
                      {min_heap_size,233},
                      {fullsweep_after,65535},
                      {minor_gcs,64637}]},
 {suspending,[]}]
```

The only process increasing in memory is the shell process (because it has to store the shell history of the call responses). Total memory usage for the `foo_meck` process afterwards is 16Kb which is about the same as when it is started (checked in Observer).

**Comment by michalrw** [comment]
Thank you for your answer. I found a mistake in my code. I had an error in meck:new which was cached. Then meck:expect created meck without no_history option. I had no idea that I can call meck:expect without meck:new (or after meck:new failure) so when meck worked, I though than meck:new was ok.

**Comment by eproxus** [comment]
Yeah, that's a tricky one. We added implicit mock creation to reduce the number of calls you have to do to setup tests.
