### ISSUE TITLE
compile forms error while mocking own written module

### ISSUE THREAD

**Issue by vipinsingh211** [eproxus/meck#174]
Trying to mock own written module which is internally called by the module for which I am writing UTs. But, the UT is failing below error:
```erlang
**error:{compile_forms,{error,[{"cover.erl",
                        [{75,erl_lint,
                          {undefined_function,{compile_beam,2}}}]}],
                      []}}
```

## Versions

**Meck version:** [0.8.2]
**Erlang version:** [19]

**Comment by eproxus** [comment]
Looks like your Erlang installation does not contain the `erl_lint` module, which is odd considering that it exist in the standard library. What OS are you on? How is Erlang installed? What's the output of `rp(code:get_path()).` in the Erlang shell?

**Comment by vipinsingh211** [comment]
Thanks for the reply, I was able to solve the problem by upgrading meck version from 0.8.2 to latest(master). Seems, the older version was not compatible with Erlang 19.

**Comment by eproxus** [comment]
Yeah, forgot to check your actual version 😄 0.8.2 has only been tested up to Erlang 17.0. You should be okay on 0.8.4 too
