### ISSUE TITLE
OTP 20 support: release new version on hex

### ISSUE THREAD

**Issue by tompave** [eproxus/meck#177]
[`meck 0.8.4`](https://hex.pm/packages/meck/0.8.4) seems to not be fully compatible with OTP 20, as originally reported on https://github.com/jjh42/mock/issues/66.

The https://github.com/eproxus/meck/commit/7c5548e1a971790f9c8990cc4767df0619b7587b commit on master fixes the issue. Verified by installing `meck` from github.

Is there any plan to release soon a new version on hex?

**Comment by eproxus** [comment]
0.8.5 is up on Hex now, please try it!

**Comment by eproxus** [comment]
And thanks for testing the new version 😄

**Comment by eproxus** [comment]
0.8.6 has an additional minor fix as well.

**Comment by tompave** [comment]
Thank you for the fix!
If you're interested in how i tested the bew version, you can check the red/green travis builds on this PR:
https://github.com/tompave/fun_with_flags/pull/9

**Comment by tompave** [comment]
Just updated to `0.8.6` from Hex.pm. All tests passing, thanks!

**Comment by eproxus** [comment]
Thanks for testing!
