### ISSUE TITLE
Enhancement: Mocking within the current module

### ISSUE THREAD

**Issue by lfmunoz** [eproxus/meck#189]
How do I mock a function that is within the current module?

In the code below I want to check that close_connection() is being called

```
close_connection() ->
  self() ! stop

check_retries(State) ->
if  State#user_state.retries < ?RETRIES ->
      true;
true ->
      close_connection(),
      false
end

-ifdef(EUNIT). 

retries_test() ->
     ??? How to mock in the current module?
  meck:expect(?MODULE, close_connection, fun() -> true end),
  check_retries(State),
  assert(meck:validate(close_connection)).

-endif.
```

**Comment by edgurgel** [comment]
You probably need to use the fully qualified name inside your own module `YourModule:close_connection()`

**Comment by eproxus** [comment]
As @edgurgel said, local calls jump directly in the byte code. Even if Meck replaces the function, the module doesn't call the new one, it just jumps to the old internal version.
