### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [eproxus/meck#222]
Would it be possible to tag a release, here and in Hex.pm?

Many thanks.

If possible:

- [ ] postpone until https://github.com/eproxus/meck/pull/223 is merged

**Comment by eproxus** [comment]
I've cut [0.9.1](https://github.com/eproxus/meck/releases/tag/0.9.1). See comments on #223 about why it is not merged yet.

**Comment by paulo-ferraz-oliveira** [comment]
Great, thanks. This will get rid of `hamcrest` already 😄.

**Comment by eproxus** [comment]
[0.9.2](https://github.com/eproxus/meck/releases/tag/0.9.2) is released with #223 included.
