### ISSUE TITLE
New release for erlang 27

### ISSUE THREAD

**Issue by systream** [eproxus/meck#247]
As of https://github.com/eproxus/meck/commit/dfb47c544bdf14b5c26ff2651cf9339dbbe2f50e commit meck does not support erlang 24. Could you please add a new tag for the new commit and as well to the previous one https://github.com/eproxus/meck/commit/aa278c1e9f45ed5cdf32afc4797cc67e19551111.

@eproxus 
Thanks

**Comment by eproxus** [comment]
I'm planning to make a new release soon, which will have a new tag. I'm not planning on releasing an intermediate version with all commits previous to removing support for OTP 24. The last official version that supports that will be the old 0.9.2 version.
